TRUNCATE TABLE image;
TRUNCATE TABLE avancement;
TRUNCATE TABLE signalement_statut;
TRUNCATE TABLE statut_signalement;
TRUNCATE table signalement;
TRUNCATE TABLE entreprise;
TRUNCATE TABLE tentative;
TRUNCATE TABLE users;
TRUNCATE TABLE profil;