DROP TABLE image;
drop TABLE avancement;
DROP TABLE signalement_statut;
DROP TABLE statut_signalement;
drop table signalement;
DROP TABLE entreprise;
DROP TABLE tentative;
DROP TABLE users;
DROP TABLE profil;